llm_endpoint: "https://your-llm-endpoint.com"
llm_model_name: "your-model-name"
llm_api_key: "your-api-key"

capabilities:
  image_tools:
    create_image_from_prompt:
      ic_endpoint: "https://your-ic-endpoint.com"
      api_key: "your-ic-api-key"